<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- TODO: enable XML doc -->
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <!-- CS1591: Missing XML doc comment -->
    <WarningsNotAsErrors>CS1591</WarningsNotAsErrors>
  </PropertyGroup>

</Project>
