using System.Text;

using GitHooks.Infrastructure.Hooks;

namespace GitHooks.Infrastructure.Scaffold;

/// <summary>
/// Default implementation of <see cref="IGitHookScaffolder"/>.
/// </summary>
public sealed class GitHookScaffolder : IGitHookScaffolder
{
    /// <inheritdoc/>
    public async Task<GitHookScaffoldResult> CreateScaffoldAsync(string repositoryRootPath, string hooksPath, IReadOnlyCollection<GitHook> hooks, bool overwrite, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(hooksPath))
        {
            return GitHookScaffoldResult.Failure("hooks-path cannot be empty.");
        }

        // Resolve hooksPath relative to the repository root so the tool behaves consistently
        // regardless of which subfolder it is invoked from.
        var resolvedHooksPath = Path.GetFullPath(hooksPath, repositoryRootPath);

        try
        {
            _ = Directory.CreateDirectory(resolvedHooksPath);

            var createdHooks = new List<GitHook>(hooks.Count);

            foreach (var hook in hooks)
            {
                cancellationToken.ThrowIfCancellationRequested();

                var hookFilePath = Path.Combine(resolvedHooksPath, hook.Name);
                var yamlFilePath = Path.Combine(resolvedHooksPath, $"{hook.Name}.yaml");

                if (File.Exists(hookFilePath) && !overwrite)
                {
                    return GitHookScaffoldResult.Failure($"Scaffold file already exists: {hookFilePath}.");
                }

                if (File.Exists(yamlFilePath) && !overwrite)
                {
                    return GitHookScaffoldResult.Failure($"Scaffold file already exists: {yamlFilePath}.");
                }

                // BuildHookTemplate receives the original (relative) hooksPath so the generated
                // bash script's --file argument stays relative to the repository root, which is
                // the working directory when Git invokes the hook.
                await File.WriteAllTextAsync(hookFilePath, BuildHookTemplate(hooksPath, hook.Name), new UTF8Encoding(false), cancellationToken);
                await File.WriteAllTextAsync(yamlFilePath, BuildYamlTemplate(hook), new UTF8Encoding(false), cancellationToken);
                createdHooks.Add(hook);
            }

            return GitHookScaffoldResult.Success(createdHooks, resolvedHooksPath);
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex) when (
            ex is IOException
            or UnauthorizedAccessException
            or ArgumentException
            or NotSupportedException
            or System.Security.SecurityException
        )
        {
            return GitHookScaffoldResult.Failure($"Failed to create hook scaffold files: {ex.Message}");
        }
    }

    private static string BuildHookTemplate(string hooksPath, string hookName)
    {
        return $"""
            #!/usr/bin/env bash
            # Generated by githooks tool
            # Hook: {hookName}
            # YAML path resolved from the repository root so the script does not depend on the current working directory.

            set -e

            dotnet run --project "src/GitHooks" --no-launch-profile -- run --file "{hooksPath}/{hookName}.yaml"

            exit 0

            """;
    }

    private static string BuildYamlTemplate(GitHook hook)
    {
        return $"""
            # Generated by githooks tool
            # Hook: {hook.Name}
            # {hook.Description}
            # Define the steps to run for this hook below.

            steps:
              - name: example
                run: echo "Running {hook.Name} hook"

            """;
    }
}
