<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GitHooks.Diagnostics\GitHooks.Diagnostics.csproj" />
    <ProjectReference Include="..\GitHooks.Domain\GitHooks.Domain.csproj" />
  </ItemGroup>

</Project>
