<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <AssemblyName>GitHooks.Tasks</AssemblyName>
    <RootNamespace>GitHooks.Tasks</RootNamespace>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GitHooks.CommandLines\GitHooks.CommandLines.csproj" />
  </ItemGroup>

</Project>
