<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scaffold\Templates\hook.sh" />
    <EmbeddedResource Include="Scaffold\Templates\hook.yaml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GitHooks.Templates\GitHooks.Templates.csproj" />
  </ItemGroup>

</Project>
