using System.Text;

namespace GitHooks.CommandLine;

/// <summary>
/// Default implementation of <see cref="IHookFileManager"/>.
/// </summary>
public sealed class HookFileManager : IHookFileManager
{
    /// <inheritdoc/>
    public async Task<HookFileCreationResult> CreateHookFilesAsync(string hooksPath, IReadOnlyCollection<string> hookNames, bool overwrite, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(hooksPath))
        {
            return HookFileCreationResult.Failure("hooks-path cannot be empty.");
        }

        try
        {
            _ = Directory.CreateDirectory(hooksPath);

            var createdHooks = new List<string>(hookNames.Count);

            foreach (var hookName in hookNames)
            {
                cancellationToken.ThrowIfCancellationRequested();

                var hookFilePath = Path.Combine(hooksPath, hookName);
                var yamlFilePath = Path.Combine(hooksPath, $"{hookName}.yaml");

                if (File.Exists(hookFilePath) && !overwrite)
                {
                    return HookFileCreationResult.Failure($"Hook file already exists: {hookFilePath}. Use --force to overwrite.");
                }

                if (File.Exists(yamlFilePath) && !overwrite)
                {
                    return HookFileCreationResult.Failure($"Hook file already exists: {yamlFilePath}. Use --force to overwrite.");
                }

                await File.WriteAllTextAsync(hookFilePath, BuildHookTemplate(hooksPath, hookName), new UTF8Encoding(false), cancellationToken);
                await File.WriteAllTextAsync(yamlFilePath, BuildYamlTemplate(hookName), new UTF8Encoding(false), cancellationToken);
                createdHooks.Add(hookName);
            }

            return HookFileCreationResult.Success(createdHooks);
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex) when (
            ex is IOException
            or UnauthorizedAccessException
            or ArgumentException
            or NotSupportedException
            or System.Security.SecurityException
        )
        {
            return HookFileCreationResult.Failure($"Failed to create hook files: {ex.Message}");
        }
    }

    private static string BuildHookTemplate(string hooksPath, string hookName)
    {
        return $"""
            #!/usr/bin/env bash
            # Generated by githooks create
            # Hook: {hookName}
            # Expected YAML file: {hooksPath}/{hookName}.yaml
            # Development project: src/GitHooks
            # Paths are resolved from the repository root so the script does not depend on the current working directory.

            set -e

            repo_root="$(git rev-parse --show-toplevel)"
            project_path="$repo_root/src/GitHooks"
            yaml_path="$repo_root/{hooksPath}/{hookName}.yaml"

            dotnet run --project "$project_path" --no-launch-profile -- run --file "$yaml_path"

            exit 0
            """;
    }

    private static string BuildYamlTemplate(string hookName)
    {
        return $"""
            # Hook: {hookName}
            # Generated by githooks create
            # Define the steps to run for this hook below.

            steps:
              - name: example
                run: echo "Running {hookName} hook"
            """;
    }
}
