using System.Text;

namespace GitHooks.CommandLine;

/// <summary>
/// Default implementation of <see cref="IHookFileManager"/>.
/// </summary>
public sealed class HookFileManager : IHookFileManager
{
    /// <inheritdoc/>
    public async Task<HookFileCreationResult> CreateHookFilesAsync(string hooksPath, IReadOnlyCollection<string> hookNames, bool overwrite, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(hooksPath))
        {
            return HookFileCreationResult.Failure("hooks-path cannot be empty.");
        }

        try
        {
            _ = Directory.CreateDirectory(hooksPath);

            var createdHooks = new List<string>(hookNames.Count);

            foreach (var hookName in hookNames)
            {
                cancellationToken.ThrowIfCancellationRequested();

                var hookFilePath = Path.Combine(hooksPath, hookName);

                if (File.Exists(hookFilePath) && !overwrite)
                {
                    return HookFileCreationResult.Failure($"Hook file already exists: {hookFilePath}. Use --force to overwrite.");
                }

                await File.WriteAllTextAsync(hookFilePath, BuildHookTemplate(hookName), new UTF8Encoding(false), cancellationToken);
                createdHooks.Add(hookName);
            }

            return HookFileCreationResult.Success(createdHooks);
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex) when (
            ex is IOException
            or UnauthorizedAccessException
            or ArgumentException
            or NotSupportedException
            or System.Security.SecurityException
        )
        {
            return HookFileCreationResult.Failure($"Failed to create hook files: {ex.Message}");
        }
    }

    private static string BuildHookTemplate(string hookName)
    {
        return $"#!/usr/bin/env bash\n# Generated by githooks create\n# Hook: {hookName}\n\nset -e\n\nexit 0\n";
    }
}
