#!/usr/bin/env bash

# Generated by githooks tool v{{VERSION}}
# Hook: {{HOOK_NAME}}
# {{HOOK_DESCRIPTION}}
# YAML path resolved from the repository root so the script does not depend on the current working directory.

set -e

dotnet run --project "src/GitHooks" --no-launch-profile -- run --file "{{HOOKS_PATH}}/{{HOOK_NAME}}.yaml"

exit 0
