<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <AssemblyName>GitHooks.CommandLines</AssemblyName>
    <RootNamespace>GitHooks.CommandLines</RootNamespace>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
